name: audit
on:
  push:
    branches: [master]
    paths: ["bun.lock", "package.json"]
  pull_request: {}
  workflow_dispatch: {}
  schedule:
    - cron: "28 6 * * 4"
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.label || github.run_id }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  audit:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun audit
